[package]
name = "rust_transformers_gpt2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokenizers = "0.15.0"
ndarray = "0.15.6"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
safetensors = "0.4.0"
clap = { version = "4.4.8", features = ["derive"] }
ndarray-stats = "0.5.1" # Added for GatingLayer (QuantileExt, etc.)
sysinfo = "0.29.0" # Added for system monitoring

[[bin]]
name = "repl"
path = "src/repl.rs"

[dev-dependencies]
tempfile = "3.3.0"
