[package]
name = "tensor_core_optimized"
version = "0.1.0"
edition = "2021"

[dependencies]
libm = "0.2.8"
half = "2.2.1" # For f16/bf16 support
num-traits = "0.2" # For numeric trait bounds

[dev-dependencies]
rand = "0.8"
approx = "0.5"
